apiVersion: argoproj.io/v1alpha1 
kind: AppProject               
metadata:
  name: frontend-team          # Name of the Project (unique within ArgoCD)
  namespace: argocd            
spec:
  description: Project for frontend team apps   
  sourceRepos:                 
    - https://github.com/PreetR24/argocd-demos.git
  destinations:                
    - namespace: frontend
      server: https://172.19.0.3:6443
  clusterResourceWhitelist:    # Which cluster-wide resources are allowed (e.g., CRDs)
    - group: "*"               
      kind: "*"                
  namespaceResourceWhitelist:  # Which namespace-level resources are allowed
    - group: "*"               
      kind: "*"
  roles:                       
    - name: frontend-admins    
      description: Admins for frontend team
      policies:                
        # syntax: - p, proj:<project-name>:<role-name>, applications, <action>, <project>/<app-name>, permission(allow|deny)
        - p, proj:frontend-team:frontend-admins, applications, *, frontend-team/*, allow  # Full access to all apps in this Project, Here p = policy, proj = project, applications = resource, * = action (all actions), frontend-team/* = resource name pattern, allow = effect (allow or deny)