apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - secret.yaml

# (optional) you can put commonLabels or namespace here if you want
# commonLabels:
#   app: chai-app

images:
  - name: preetrupapara/chai-devops
    newName: preetrupapara/chai-devops
    newTag: v1.0.2
